import type { AnatomyKey } from "./data";

export type Lang = "en" | "fa";

export type TextPart = { text: string; accent?: boolean };
export type HeroWord = { text: string; highlight?: boolean };

/** Every user-visible string on the landing page, in both languages. */
const en = {
  meta: { title: "Lumière Dental — Expert Dental Care for a Brighter Smile" },
  langLabel: "Language",
  brand: "Lumière Dental",
  brandHome: "Lumière Dental — home",
  nav: [
    { label: "Home", href: "#top" },
    { label: "Services", href: "#services" },
    { label: "About", href: "#about" },
    { label: "Reviews", href: "#reviews" },
    { label: "Contact", href: "#contact" },
  ],
  book: "Book Appointment",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  navPrimary: "Primary",
  navMobile: "Mobile",
  headerHours: "Mon – Sat · 8:00 – 19:00 · +1 (415) 555-0142",
  stars: (n: number) => `${n} out of 5 stars`,
  strip: ["Digital 3D imaging", "Pain-free laser dentistry", "Same-day ceramics", "Clear aligners", "Sedation available", "Family friendly"],
  hero: {
    messages: ["Advanced Dental Care", "Confident Smiles", "Modern Technology", "Personalized Treatment", "Healthy Teeth for Life"],
    lines: [
      [{ text: "Expert" }, { text: "Dental" }, { text: "Care" }],
      [{ text: "for a" }, { text: "Healthier," }],
      [{ text: "Brighter", highlight: true }, { text: "Smile", highlight: true }],
    ] as HeroWord[][],
    desc: "Lumière is a modern dental studio where precision technology meets genuinely personal care. From routine check-ups to full smile design, every treatment is planned around your comfort and your long-term health.",
    explore: "Explore the Clinic",
    trust: "Trusted by",
    patients: "patients",
    trustCount: "10,000+",
    portraitAlt: "Dr. Adrian Marsh, lead dentist at Lumière Dental",
    painless: "Painless by design",
    painlessSub: "Digital anaesthesia & laser care",
    doctor: "Dr. Adrian Marsh",
    doctorSub: "DDS · 15 years of practice",
    scroll: "Scroll",
  },
  anatomy: {
    eyebrow: "Interactive anatomy",
    title: [{ text: "Understand your smile, " }, { text: "layer by layer", accent: true }] as TextPart[],
    lead: "Explore a living model of the dental arch. Select any structure to see how we protect it — from the enamel surface down to the nerve.",
    live: "Live 3D model",
    hint: "Drag to rotate · tap a point to explore",
    idleTitle: "A complete picture of oral health",
    idleBody: "Every treatment plan at Lumière begins with understanding — digital scans, 3D imaging and a clear explanation of what we see. Hover a structure to begin.",
    cross: "Cross-section reference. Highlights follow your selection so you can relate the educational diagram to the 3D model.",
    items: {
      enamel: { label: "Enamel", short: "The hardest substance in the body", description: "A translucent mineral shell that protects the crown from daily wear, temperature and acids. Enamel cannot regrow, which is why preventive care and gentle polishing matter so much." },
      dentin: { label: "Dentin", short: "The living core beneath the enamel", description: "Slightly yellow and softer than enamel, dentin gives teeth their warmth and resilience. Microscopic tubules carry sensation, which is why exposed dentin can feel sensitive." },
      pulp: { label: "Pulp", short: "Blood supply and vitality", description: "The soft chamber at the centre of the tooth houses blood vessels and connective tissue. Keeping it healthy is the goal of every restorative treatment we plan." },
      gum: { label: "Gum", short: "The seal around every tooth", description: "Healthy gingiva fits snugly around the neck of each tooth, protecting the bone underneath. Firm, pale-pink tissue is the foundation of a long-lasting smile." },
      root: { label: "Root", short: "Anchored deep in the jaw", description: "Two-thirds of a tooth sits below the surface. Roots are covered in cementum and held by ligament fibres, which is what implants are designed to replicate." },
      nerve: { label: "Nerve", short: "Sensation and feedback", description: "Fine nerve fibres enter through the apex of each root. Modern root canal therapy gently treats this canal while preserving the natural tooth." },
    } as Record<AnatomyKey, { label: string; short: string; description: string }>,
  },
  services: {
    eyebrow: "Our services",
    title: [{ text: "Complete care, " }, { text: "thoughtfully delivered", accent: true }] as TextPart[],
    lead: "Six specialities under one roof, so your care is coordinated by a team that knows your history — not a referral chain.",
    plan: "Plan a consultation",
    more: "Learn more",
    items: [
      { title: "General Dentistry", text: "Comprehensive examinations, gentle hygiene visits and preventive care that keeps small issues from becoming big ones." },
      { title: "Cosmetic Dentistry", text: "Veneers, bonding and digital smile design — subtle, natural improvements planned with you in 3D before we begin." },
      { title: "Dental Implants", text: "Guided implant placement with premium titanium and ceramic restorations that look, feel and function like your own teeth." },
      { title: "Orthodontics", text: "Clear aligners and discreet braces for adults and teens, monitored remotely so you visit less and smile sooner." },
      { title: "Root Canal", text: "Microscope-assisted endodontics that saves natural teeth comfortably — usually in a single, calm appointment." },
      { title: "Teeth Whitening", text: "Clinically supervised whitening calibrated to your enamel, for a brighter result without sensitivity." },
    ],
    footerTitle: "Services",
  },
  reviews: {
    eyebrow: "Patient stories",
    title: [{ text: "Smiles we are " }, { text: "proud of", accent: true }] as TextPart[],
    photoAlt: "A patient smiling after treatment at Lumière Dental",
    real: "Real patients, real results",
    consent: "Photographed with consent",
    pill: "4.9 ★ · 1,200+ reviews",
    tabs: "Testimonials",
    tab: (n: number) => `Testimonial ${n}`,
    prev: "Previous testimonial",
    next: "Next testimonial",
    items: [
      { quote: "I had avoided dentists for years. The team explained everything on the 3D scan before touching a single tooth, and the implant feels completely natural. I actually look forward to my visits now.", name: "Sophie Laurent", treatment: "Dental implant & crown" },
      { quote: "The whitening was calibrated to my enamel so there was zero sensitivity. Results looked natural, not artificial — exactly what I asked for.", name: "Marcus Chen", treatment: "Teeth whitening" },
      { quote: "Clear aligners with remote check-ins meant fewer trips across town. Eighteen months later my bite is corrected and the whole process was remarkably calm.", name: "Daniel Rossi", treatment: "Orthodontics · clear aligners" },
      { quote: "A root canal in one appointment, pain-free. I didn't think those words could go together. The clinic itself feels more like a design studio than a surgery.", name: "Amara Okafor", treatment: "Root canal therapy" },
    ],
  },
  stats: {
    eyebrow: "Why Lumière",
    title: [{ text: "Trusted care, " }, { text: "measured", accent: true }] as TextPart[],
    items: [
      { label: "Years of experience" },
      { label: "Happy patients" },
      { label: "Patient satisfaction" },
      { label: "Average rating" },
    ],
  },
  results: {
    eyebrow: "Real results",
    title: [{ text: "Before and after, " }, { text: "side by side", accent: true }] as TextPart[],
    lead: "Drag the divider to compare. Every case is planned digitally and photographed under the same studio lighting for an honest comparison.",
    slider: "Before and after comparison",
    beforeAlt: "Smile before treatment, with yellow stained teeth",
    afterAlt: "The same smile after treatment, with bright white teeth",
    before: "Before",
    after: "After",
    caseEyebrow: "Case study 24",
    caseTitle: "Professional whitening after years of staining",
    caseBody: "A deep hygiene visit followed by clinically supervised whitening calibrated to the enamel — no veneers, no sensitivity, the patient's own teeth.",
    rows: [
      { label: "Concern", value: "Yellowing, surface stains, dull enamel" },
      { label: "Treatment", value: "Hygiene + supervised whitening" },
      { label: "Duration", value: "2 visits over 2 weeks" },
      { label: "Outcome", value: "Six shades brighter, natural gloss" },
    ],
    discuss: "Discuss your case",
  },
  booking: {
    eyebrow: "Appointments",
    title: [{ text: "Book your visit in " }, { text: "under a minute", accent: true }] as TextPart[],
    lead: "Choose a convenient time and let our team take care of the rest. We confirm by phone or message within one working hour.",
    roomAlt: "A bright treatment room at Lumière Dental",
    calm: "Calm rooms. Clear plans. No surprises.",
    calmBody: "Transparent pricing is shared before any treatment begins, and every room is designed for comfort.",
    chips: ["Same-week availability", "Insurance friendly", "Free parking"],
    thanks: (first: string) => (first ? `Thank you, ${first}.` : "Thank you."),
    receivedBefore: "Your request for ",
    receivedAfter: " has been received. Our coordinator will confirm the exact slot shortly.",
    another: "Book another appointment",
    formTitle: "Request an appointment",
    requiredNote: "Fields marked with * are required.",
    name: "Full name *",
    namePh: "Alex Morgan",
    phone: "Phone *",
    phonePh: "+1 (415) 555-0142",
    treatment: "Treatment",
    treatments: ["Consultation", "General check-up & hygiene", "Cosmetic dentistry", "Dental implants", "Orthodontics", "Root canal", "Teeth whitening"],
    date: "Preferred date *",
    time: "Preferred time",
    privacy: "Your details are encrypted and never shared.",
  },
  about: {
    eyebrow: "About the clinic",
    title: [{ text: "More than a " }, { text: "dental clinic", accent: true }] as TextPart[],
    lead: "Lumière was founded on a simple idea: that exceptional dentistry should feel calm, transparent and genuinely human. Fifteen years later, that idea still shapes every room, every instrument and every conversation.",
    meet: "Meet the team",
    clinicAlt: "The light-filled reception and treatment rooms at Lumière Dental",
    studio: "Our studio, Marina District",
    consultAlt: "A dentist reviewing a digital scan together with a patient",
    planning: "Digital smile planning",
    promiseEyebrow: "Our promise",
    promise: "You will always understand what we recommend, and why.",
    promiseBody: "Clear explanations, honest pricing, and the time to decide — that is how trust is built, one visit at a time.",
    founder: "Dr. Adrian Marsh",
    founderRole: "Founder & Lead Dentist",
    values: [
      { title: "15 years of expertise", text: "Founded in 2011, our clinicians have completed over 40,000 treatments across every speciality." },
      { title: "Technology that reassures", text: "Intra-oral scanners, 3D CBCT imaging and in-house ceramics shorten treatment and remove guesswork." },
      { title: "A team that listens", text: "Specialists, hygienists and coordinators work as one team, so your plan is consistent from first call to last visit." },
      { title: "Care that is personal", text: "No templates. Every plan is built around your anatomy, your goals and the pace you are comfortable with." },
    ],
  },
  contact: {
    eyebrow: "Visit us",
    title: [{ text: "Find us in the " }, { text: "Marina District", accent: true }] as TextPart[],
    lead: "Two minutes from the Chestnut Street tram stop with validated parking beneath the building.",
    rows: [
      { k: "Address", v: "1210 Chestnut Street, Suite 300", s: "San Francisco, CA 94123" },
      { k: "Phone", v: "+1 (415) 555-0142", s: "Emergency line available 24/7" },
      { k: "Email", v: "hello@lumieredental.com", s: "We reply within one working day" },
      { k: "Opening hours", v: "Mon – Fri 8:00 – 19:00", s: "Saturday 9:00 – 15:00 · Sunday closed" },
    ],
    mapTitle: "Lumière Dental Studio",
    mapSub: "1210 Chestnut Street · Open today until 19:00",
    directions: "Get directions",
  },
  footer: {
    blurb: "A modern dental studio in San Francisco combining advanced technology with calm, personal care — for healthier teeth and brighter smiles that last.",
    instagram: "Instagram",
    facebook: "Facebook",
    linkedin: "LinkedIn",
    navigation: "Navigation",
    contact: "Contact",
    rights: (year: number) => `© ${year} Lumière Dental Studio. All rights reserved.`,
    privacy: "Privacy",
    terms: "Terms",
    accessibility: "Accessibility",
    toTop: "Back to top",
    address: "1210 Chestnut Street, Suite 300",
    hours: "Mon – Fri 8:00 – 19:00",
  },
};

const fa: typeof en = {
  meta: { title: "لومیر دنتال — مراقبت تخصصی دندان برای لبخندی درخشان" },
  langLabel: "زبان",
  brand: "لومیر دنتال",
  brandHome: "لومیر دنتال — خانه",
  nav: [
    { label: "خانه", href: "#top" },
    { label: "خدمات", href: "#services" },
    { label: "درباره", href: "#about" },
    { label: "نظرات", href: "#reviews" },
    { label: "تماس", href: "#contact" },
  ],
  book: "رزرو نوبت",
  openMenu: "باز کردن منو",
  closeMenu: "بستن منو",
  navPrimary: "اصلی",
  navMobile: "موبایل",
  headerHours: "دوشنبه تا شنبه · 8:00 – 19:00 · +1 (415) 555-0142",
  stars: (n: number) => `${n} از 5 ستاره`,
  strip: ["تصویربرداری سه‌بعدی", "دندان‌پزشکی لیزری بدون درد", "سرامیک در همان روز", "الاینر شفاف", "آرام‌بخشی در دسترس", "مناسب خانواده"],
  hero: {
    messages: ["مراقبت پیشرفته دندان", "لبخندهای مطمئن", "فناوری مدرن", "درمان شخصی‌سازی‌شده", "دندان‌های سالم برای همیشه"],
    lines: [
      [{ text: "مراقبت" }, { text: "تخصصی" }, { text: "دندان" }],
      [{ text: "برای" }, { text: "لبخندی" }],
      [{ text: "سالم‌تر", highlight: true }, { text: "و درخشان‌تر", highlight: true }],
    ],
    desc: "لومیر استودیویی مدرن برای دندان‌پزشکی است؛ جایی که فناوری دقیق با مراقبتی واقعاً شخصی همراه می‌شود. از معاینهٔ دوره‌ای تا طراحی کامل لبخند، هر درمان بر اساس راحتی شما و سلامت بلندمدت‌تان برنامه‌ریزی می‌شود.",
    explore: "آشنایی با کلینیک",
    trust: "مورد اعتماد",
    patients: "بیمار",
    trustCount: "10,000+",
    portraitAlt: "دکتر آدریان مارش، دندان‌پزشک ارشد لومیر دنتال",
    painless: "بدون درد، از اساس",
    painlessSub: "بی‌حسی دیجیتال و درمان با لیزر",
    doctor: "دکتر آدریان مارش",
    doctorSub: "دکتری دندان‌پزشکی · 15 سال تجربه",
    scroll: "پیمایش",
  },
  anatomy: {
    eyebrow: "آناتومی تعاملی",
    title: [{ text: "لبخندتان را بشناسید، " }, { text: "لایه به لایه", accent: true }],
    lead: "یک مدل زنده از قوس دندانی را ببینید. هر ساختار را انتخاب کنید تا نشان دهیم چطور از آن محافظت می‌کنیم — از سطح مینا تا عصب.",
    live: "مدل زندهٔ سه‌بعدی",
    hint: "بکشید تا بچرخد · برای دیدن جزئیات یک نقطه را لمس کنید",
    idleTitle: "تصویری کامل از سلامت دهان",
    idleBody: "هر برنامهٔ درمانی در لومیر با فهمیدن آغاز می‌شود — اسکن دیجیتال، تصویربرداری سه‌بعدی و توضیحی روشن از آنچه می‌بینیم. برای شروع، روی یک ساختار مکث کنید.",
    cross: "مرجع برش عرضی. هایلایت‌ها با انتخاب شما همراه می‌شوند تا نمودار آموزشی را با مدل سه‌بعدی تطبیق دهید.",
    items: {
      enamel: { label: "مینا", short: "سخت‌ترین مادهٔ بدن", description: "پوسته‌ای معدنی و نیمه‌شفاف که تاج دندان را در برابر سایش روزانه، دما و اسیدها حفظ می‌کند. مینا دوباره رشد نمی‌کند؛ به همین دلیل مراقبت پیشگیرانه و پولیش ملایم این‌قدر مهم است." },
      dentin: { label: "عاج", short: "هستهٔ زنده زیر مینا", description: "عاج کمی زرد و نرم‌تر از میناست و به دندان گرما و انعطاف می‌دهد. لوله‌های میکروسکوپی حس را منتقل می‌کنند؛ به همین دلیل عاجِ بدون پوشش حساس می‌شود." },
      pulp: { label: "پالپ", short: "خون‌رسانی و حیات دندان", description: "حفرهٔ نرم مرکز دندان، رگ‌های خونی و بافت همبند را در خود دارد. سالم نگه‌داشتن آن، هدف هر درمان ترمیمی است که طراحی می‌کنیم." },
      gum: { label: "لثه", short: "مهر دور هر دندان", description: "لثهٔ سالم دور طوق هر دندان می‌نشیند و از استخوان زیر آن محافظت می‌کند. بافتی سفت و صورتی‌رنگ، پایهٔ لبخندی ماندگار است." },
      root: { label: "ریشه", short: "لنگر عمیق در فک", description: "دو سوم دندان زیر سطح قرار دارد. ریشه‌ها با سمان پوشیده شده‌اند و با الیاف رباط نگه داشته می‌شوند؛ همان چیزی که ایمپلنت برای بازسازی‌اش طراحی شده است." },
      nerve: { label: "عصب", short: "حس و بازخورد", description: "رشته‌های ظریف عصب از نوک هر ریشه وارد می‌شوند. درمان ریشهٔ مدرن این کانال را با ملایمت درمان می‌کند و دندان طبیعی را حفظ می‌کند." },
    },
  },
  services: {
    eyebrow: "خدمات ما",
    title: [{ text: "مراقبت کامل، " }, { text: "با دقت ارائه شده", accent: true }],
    lead: "شش تخصص زیر یک سقف، تا مراقبت‌تان را تیمی هماهنگ کند که سابقهٔ شما را می‌شناسد — نه زنجیره‌ای از ارجاع‌ها.",
    plan: "برنامه‌ریزی مشاوره",
    more: "بیشتر بدانید",
    items: [
      { title: "دندان‌پزشکی عمومی", text: "معاینه‌های جامع، جرم‌گیری ملایم و مراقبت پیشگیرانه که نمی‌گذارد مسئله‌های کوچک بزرگ شوند." },
      { title: "دندان‌پزشکی زیبایی", text: "ونیر، باندینگ و طراحی دیجیتال لبخند — بهبودهایی ظریف و طبیعی که پیش از شروع، همراه شما در مدل سه‌بعدی برنامه‌ریزی می‌شود." },
      { title: "ایمپلنت دندان", text: "کاشت هدایت‌شده با ترمیم‌های تیتانیوم و سرامیک مرغوب که مثل دندان خودتان دیده می‌شوند، حس می‌شوند و کار می‌کنند." },
      { title: "ارتودنسی", text: "الاینر شفاف و براکت‌های نامحسوس برای بزرگسالان و نوجوانان، با پیگیری از راه دور تا کمتر مراجعه کنید و زودتر لبخند بزنید." },
      { title: "درمان ریشه", text: "اندودانتیکس با میکروسکوپ که دندان طبیعی را راحت نجات می‌دهد — معمولاً در یک جلسهٔ آرام." },
      { title: "سفید کردن دندان", text: "سفید کردن زیر نظر پزشک، تنظیم‌شده با مینای شما، برای نتیجه‌ای درخشان‌تر بدون حساسیت." },
    ],
    footerTitle: "خدمات",
  },
  reviews: {
    eyebrow: "داستان بیماران",
    title: [{ text: "لبخندهایی که به آن‌ها " }, { text: "افتخار می‌کنیم", accent: true }],
    photoAlt: "لبخند یک بیمار پس از درمان در لومیر دنتال",
    real: "بیماران واقعی، نتیجه‌های واقعی",
    consent: "با رضایت عکس‌برداری شده",
    pill: "4.9 ★ · بیش از 1,200 نظر",
    tabs: "نظرات",
    tab: (n: number) => `نظر ${n}`,
    prev: "نظر قبلی",
    next: "نظر بعدی",
    items: [
      { quote: "سال‌ها از دندان‌پزشک دوری می‌کردم. تیم همه‌چیز را روی اسکن سه‌بعدی توضیح داد، پیش از آنکه به یک دندان دست بزند، و ایمپلنت کاملاً طبیعی حس می‌شود. حالا حتی منتظر مراجعه‌هایم هستم.", name: "Sophie Laurent", treatment: "ایمپلنت و روکش" },
      { quote: "سفید کردن با مینای من تنظیم شد و هیچ حساسیتی نداشتم. نتیجه طبیعی بود، نه مصنوعی — دقیقاً همان چیزی که خواسته بودم.", name: "Marcus Chen", treatment: "سفید کردن دندان" },
      { quote: "الاینر شفاف با پیگیری از راه دور یعنی رفت‌وآمد کمتر در شهر. هجده ماه بعد بایت من اصلاح شده و کل روند به‌شکل شگفت‌انگیزی آرام بود.", name: "Daniel Rossi", treatment: "ارتودنسی · الاینر شفاف" },
      { quote: "درمان ریشه در یک جلسه و بدون درد. فکر نمی‌کردم این واژه‌ها کنار هم بنشینند. خود کلینیک بیشتر شبیه استودیوی طراحی است تا مطب.", name: "Amara Okafor", treatment: "درمان ریشه" },
    ],
  },
  stats: {
    eyebrow: "چرا لومیر",
    title: [{ text: "مراقبتی قابل اعتماد، " }, { text: "با عدد", accent: true }],
    items: [
      { label: "سال تجربه" },
      { label: "بیمار راضی" },
      { label: "رضایت بیماران" },
      { label: "میانگین امتیاز" },
    ],
  },
  results: {
    eyebrow: "نتایج واقعی",
    title: [{ text: "قبل و بعد، " }, { text: "کنار هم", accent: true }],
    lead: "جداکننده را بکشید و مقایسه کنید. هر پرونده دیجیتال برنامه‌ریزی می‌شود و زیر نور یکسان استودیو عکس می‌گیرد تا مقایسه صادقانه باشد.",
    slider: "مقایسهٔ قبل و بعد",
    beforeAlt: "لبخند پیش از درمان، با دندان‌های زرد و جرم‌گرفته",
    afterAlt: "همان لبخند پس از درمان، با دندان‌های روشن و درخشان",
    before: "قبل",
    after: "بعد",
    caseEyebrow: "پروندهٔ ۲۴",
    caseTitle: "سفید کردن حرفه‌ای پس از سال‌ها تغییر رنگ",
    caseBody: "یک جلسهٔ بهداشت عمیق و سپس سفید کردن زیر نظر پزشک، تنظیم‌شده با مینا — بدون ونیر، بدون حساسیت، دندان‌های خود بیمار.",
    rows: [
      { label: "نگرانی", value: "زردی، لکه‌های سطحی، مینای مات" },
      { label: "درمان", value: "بهداشت + سفید کردن نظارت‌شده" },
      { label: "مدت", value: "2 جلسه در 2 هفته" },
      { label: "نتیجه", value: "شش درجه روشن‌تر، درخشش طبیعی" },
    ],
    discuss: "دربارهٔ پرونده‌تان صحبت کنیم",
  },
  booking: {
    eyebrow: "نوبت‌ها",
    title: [{ text: "مراجعه‌تان را " }, { text: "در کمتر از یک دقیقه", accent: true }, { text: " رزرو کنید" }],
    lead: "زمان مناسب را انتخاب کنید و بقیه را به تیم ما بسپارید. تا یک ساعت کاری، با تلفن یا پیام تأیید می‌کنیم.",
    roomAlt: "اتاق درمان روشن در لومیر دنتال",
    calm: "اتاق‌های آرام. برنامهٔ روشن. بدون غافلگیری.",
    calmBody: "قیمت شفاف پیش از شروع هر درمان گفته می‌شود و هر اتاق برای راحتی طراحی شده است.",
    chips: ["نوبت در همان هفته", "هماهنگ با بیمه", "پارکینگ رایگان"],
    thanks: (first: string) => (first ? `${first} عزیز، سپاسگزاریم.` : "سپاسگزاریم."),
    receivedBefore: "درخواست شما برای ساعت ",
    receivedAfter: " ثبت شد. هماهنگ‌کننده به‌زودی زمان دقیق را تأیید می‌کند.",
    another: "رزرو یک نوبت دیگر",
    formTitle: "درخواست نوبت",
    requiredNote: "فیلدهای ستاره‌دار ضروری‌اند.",
    name: "نام و نام خانوادگی *",
    namePh: "سارا محمدی",
    phone: "تلفن *",
    phonePh: "+1 (415) 555-0142",
    treatment: "درمان",
    treatments: ["مشاوره", "معاینه و بهداشت", "دندان‌پزشکی زیبایی", "ایمپلنت دندان", "ارتودنسی", "درمان ریشه", "سفید کردن دندان"],
    date: "تاریخ ترجیحی *",
    time: "ساعت ترجیحی",
    privacy: "اطلاعات شما رمزنگاری می‌شود و هرگز به اشتراک گذاشته نمی‌شود.",
  },
  about: {
    eyebrow: "دربارهٔ کلینیک",
    title: [{ text: "بیش از یک " }, { text: "کلینیک دندان‌پزشکی", accent: true }],
    lead: "لومیر بر یک ایدهٔ ساده بنا شد: دندان‌پزشکی ممتاز باید آرام، شفاف و واقعاً انسانی باشد. پانزده سال بعد، همین ایده هنوز هر اتاق، هر ابزار و هر گفتگو را شکل می‌دهد.",
    meet: "آشنایی با تیم",
    clinicAlt: "پذیرش پرنور و اتاق‌های درمان لومیر دنتال",
    studio: "استودیوی ما، منطقهٔ مارینا",
    consultAlt: "دندان‌پزشکی که اسکن دیجیتال را همراه بیمار بررسی می‌کند",
    planning: "طراحی دیجیتال لبخند",
    promiseEyebrow: "قول ما",
    promise: "همیشه خواهید فهمید چه پیشنهادی می‌دهیم، و چرا.",
    promiseBody: "توضیح روشن، قیمت صادقانه، و زمان برای تصمیم — اعتماد این‌طور ساخته می‌شود، جلسه به جلسه.",
    founder: "دکتر آدریان مارش",
    founderRole: "بنیان‌گذار و دندان‌پزشک ارشد",
    values: [
      { title: "15 سال تخصص", text: "از سال 2011، پزشکان ما بیش از 40,000 درمان را در همهٔ تخصص‌ها انجام داده‌اند." },
      { title: "فناوری که اطمینان می‌دهد", text: "اسکنر داخل دهانی، تصویربرداری CBCT سه‌بعدی و سرامیک داخل کلینیک، درمان را کوتاه‌تر و حدس را حذف می‌کند." },
      { title: "تیمی که گوش می‌دهد", text: "متخصصان، بهداشتکاران و هماهنگ‌کنندگان یک تیم‌اند، تا برنامهٔ شما از اولین تماس تا آخرین مراجعه یکدست بماند." },
      { title: "مراقبتی که شخصی است", text: "قالب آماده وجود ندارد. هر برنامه بر اساس آناتومی شما، هدف‌هایتان و سرعتی که با آن راحتید ساخته می‌شود." },
    ],
  },
  contact: {
    eyebrow: "به ما سر بزنید",
    title: [{ text: "ما را در " }, { text: "منطقهٔ مارینا", accent: true }, { text: " پیدا کنید" }],
    lead: "دو دقیقه تا ایستگاه تراموای خیابان چست‌نات، با پارکینگ معتبر زیر ساختمان.",
    rows: [
      { k: "نشانی", v: "1210 Chestnut Street, Suite 300", s: "سان‌فرانسیسکو، کالیفرنیا 94123" },
      { k: "تلفن", v: "+1 (415) 555-0142", s: "خط اورژانس، شبانه‌روزی" },
      { k: "ایمیل", v: "hello@lumieredental.com", s: "تا یک روز کاری پاسخ می‌دهیم" },
      { k: "ساعات کاری", v: "دوشنبه تا جمعه 8:00 – 19:00", s: "شنبه 9:00 – 15:00 · یکشنبه تعطیل" },
    ],
    mapTitle: "استودیو دندان‌پزشکی لومیر",
    mapSub: "1210 Chestnut Street · امروز تا 19:00 باز است",
    directions: "مسیریابی",
  },
  footer: {
    blurb: "استودیویی مدرن برای دندان‌پزشکی در سان‌فرانسیسکو که فناوری پیشرفته را با مراقبتی آرام و شخصی همراه می‌کند — برای دندان‌هایی سالم‌تر و لبخندهایی درخشان‌تر که می‌مانند.",
    instagram: "اینستاگرام",
    facebook: "فیسبوک",
    linkedin: "لینکدین",
    navigation: "ناوبری",
    contact: "تماس",
    rights: (year: number) => `© ${year} استودیو دندان‌پزشکی لومیر. همهٔ حقوق محفوظ است.`,
    privacy: "حریم خصوصی",
    terms: "شرایط",
    accessibility: "دسترسی‌پذیری",
    toTop: "بازگشت به بالا",
    address: "1210 Chestnut Street, Suite 300",
    hours: "دوشنبه تا جمعه 8:00 – 19:00",
  },
};

export const COPY: Record<Lang, typeof en> = { en, fa };
export type Copy = typeof en;
