import type { AnatomyKey } from "./data";

export type Lang = "en" | "fa";

export type TextPart = { text: string; accent?: boolean };
export type HeroWord = { text: string; highlight?: boolean };

/** Every user-visible string on the landing page, in both languages. */
const en = {
  meta: { title: "Clinic Farda — Thoughtful dentistry in Saadat Abad, Tehran" },
  langLabel: "Language",
  brand: "Clinic Farda",
  brandHome: "Clinic Farda — home",
  nav: [
    { label: "Home", href: "#top" },
    { label: "Services", href: "#services" },
    { label: "About", href: "#about" },
    { label: "Reviews", href: "#reviews" },
    { label: "Contact", href: "#contact" },
  ],
  book: "Book a visit",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  navPrimary: "Primary",
  navMobile: "Mobile",
  headerHours: "Sat – Wed · 8:30 – 20:00 · 021-2239 4040",
  stars: (n: number) => `${n} out of 5 stars`,
  hero: {
    messages: ["Check-ups and scaling", "Implants and crowns", "Composite and laminate", "Orthodontics", "Smile design"],
    lines: [
      [{ text: "Thoughtful" }, { text: "dental" }, { text: "care" }],
      [{ text: "for" }, { text: "a" }, { text: "calmer," }],
      [{ text: "lasting", highlight: true }, { text: "smile", highlight: true }],
    ] as HeroWord[][],
    desc: "Clinic Farda is a dental practice in Saadat Abad. We start with a proper examination, show you what we see, and only then suggest treatment — from scaling and root canals to implants, veneers and braces.",
    explore: "About the clinic",
    trust: "Trusted by",
    patients: "patients",
    trustCount: "8,000+",
    portraitAlt: "Dr. Leila Farda, dentist and founder of Clinic Farda",
    painless: "Nothing starts in a hurry",
    painlessSub: "You see the plan before we begin",
    doctor: "Dr. Leila Farda",
    doctorSub: "Dentist · 12 years in practice",
    scroll: "Scroll",
  },
  anatomy: {
    eyebrow: "Tooth anatomy",
    title: [{ text: "A closer look at " }, { text: "the smile", accent: true }] as TextPart[],
    lead: "A model of the arch, gum and teeth. Choose a part to read what it does in treatment, from the enamel down to the nerve.",
    live: "Live 3D model",
    hint: "Drag to rotate · tap a point",
    idleTitle: "Pick any part of the tooth",
    idleBody: "The note stays beside the model, so you can switch between enamel, dentin, pulp, gum, root and nerve without hunting up and down the page.",
    cross: "A simple cross-section. The highlight follows whatever you have selected.",
    items: {
      enamel: {
        label: "Enamel",
        short: "The outer shell",
        description: "Enamel is the hard, translucent cover of the crown. It does not grow back. That is why we are careful with scaling, whitening and anything that touches the surface.",
      },
      dentin: {
        label: "Dentin",
        short: "The layer under the enamel",
        description: "Dentin is slightly yellow and full of tiny tubules. When enamel wears thin, this is the layer that feels cold, sweet or sensitive.",
      },
      pulp: {
        label: "Pulp",
        short: "Where the tooth is alive",
        description: "The pulp holds the blood supply and the nerve. If decay or a crack reaches it, the tooth usually needs root canal treatment if we are going to keep it.",
      },
      gum: {
        label: "Gum",
        short: "The seal around the tooth",
        description: "Healthy gum sits snugly at the neck of the tooth and protects the bone. Bleeding when you brush is often the first sign we look at during a check-up.",
      },
      root: {
        label: "Root",
        short: "The part anchored in the jaw",
        description: "Most of the tooth sits under the gum, held by ligament. An implant is meant to take this role when the root itself can no longer be saved.",
      },
      nerve: {
        label: "Nerve",
        short: "Sensation inside the canal",
        description: "The nerve enters through the tip of the root. Root canal treatment cleans this canal and seals it, so the tooth can stay in place without the pain.",
      },
    } as Record<AnatomyKey, { label: string; short: string; description: string }>,
  },
  services: {
    eyebrow: "Treatments",
    title: [{ text: "What patients " }, { text: "actually book", accent: true }] as TextPart[],
    lead: "These are the treatments we do every week at Clinic Farda. If you are not sure which one you need, the first visit is an examination — not a commitment.",
    plan: "Book an examination",
    more: "Ask about this",
    items: [
      {
        title: "Examination and scaling",
        text: "A full check-up, X-rays when they are actually useful, and a scale and polish that does not leave the gum raw. If we find decay or gum inflammation, we map the next step in the same visit.",
      },
      {
        title: "Root canal treatment",
        text: "When pain or infection has reached the nerve, we keep the tooth with root canal therapy. It is done under proper anaesthesia, usually in one or two visits, and the crown is planned afterwards — not sprung on you at the chair.",
      },
      {
        title: "Dental implants",
        text: "A titanium root and a ceramic crown for a missing tooth. Before surgery we look at bone and gum, and we tell you honestly how long healing takes before the final crown.",
      },
      {
        title: "Orthodontics",
        text: "Crowding and bite problems, with metal or ceramic braces, and clear aligners when they are genuinely the right tool. You see the plan, the likely duration, and what daily care will involve.",
      },
      {
        title: "Laminate and composite veneers",
        text: "For colour, shape or small gaps. Composite is usually quicker; ceramic laminate lasts longer. Both are matched to the neighbouring teeth so the smile does not look painted on.",
      },
      {
        title: "Whitening",
        text: "In-office bleaching for tea, coffee and tobacco stains on healthy enamel. If the teeth are sensitive, we slow the process down. We do not promise an unnatural white.",
      },
      {
        title: "Wisdom teeth",
        text: "If a wisdom tooth is impacted, pressing on its neighbour, or repeatedly inflaming the gum, we plan the extraction from the X-ray and talk through swelling, stitches and the days after.",
      },
      {
        title: "Crowns, bridges and dentures",
        text: "A crown protects a root-treated or broken tooth. When several teeth are missing, a bridge or a denture is made around your bite and your gum, not from a generic mould.",
      },
    ],
    footerTitle: "Treatments",
  },
  reviews: {
    eyebrow: "From the chair",
    title: [{ text: "What patients " }, { text: "tell us afterwards", accent: true }] as TextPart[],
    photoAlt: "A patient smiling after treatment at Clinic Farda",
    real: "Patients of the clinic",
    consent: "Shared with permission",
    pill: "4.9 ★ · 1,200+ reviews",
    tabs: "Reviews",
    tab: (n: number) => `Review ${n}`,
    prev: "Previous review",
    next: "Next review",
    items: [
      {
        quote: "I had postponed a root canal for years. Dr. Farda showed me the X-ray first and said exactly what the appointment would feel like. It was finished the same day, and I slept that night.",
        name: "Zahra Nouri",
        treatment: "Root canal and crown",
      },
      {
        quote: "I came for composite veneers and was worried they would look too white. They matched the colour to the teeth beside them. My husband did not notice the work — he just said I was smiling more.",
        name: "Sara Mohammadi",
        treatment: "Composite veneers",
      },
      {
        quote: "The lower implant started only after they had checked the bone. They told me the healing time on day one and did not rush the crown. Eating feels no different from my own tooth.",
        name: "Reza Karimi",
        treatment: "Dental implant",
      },
      {
        quote: "I started braces after thirty. We chose ceramic brackets, and at each visit they showed me the progress on a photo. The clinic itself is quiet, which mattered more than I expected.",
        name: "Maryam Hosseini",
        treatment: "Orthodontics",
      },
    ],
  },
  stats: {
    eyebrow: "Why Clinic Farda",
    title: [{ text: "Care you can " }, { text: "come back to", accent: true }] as TextPart[],
    items: [{ label: "Years in practice" }, { label: "Patients" }, { label: "Would return" }, { label: "Average rating" }],
  },
  results: {
    eyebrow: "Before and after",
    title: [{ text: "The same smile, " }, { text: "after treatment", accent: true }] as TextPart[],
    lead: "Drag the line. The left side is the teeth before scaling and whitening; the right side is the same photograph afterwards. Lips and skin are left as they were.",
    slider: "Before and after comparison",
    beforeAlt: "Smile before scaling and whitening, with stained teeth",
    afterAlt: "The same smile after treatment, with the teeth a little brighter",
    before: "Before",
    after: "After",
    caseEyebrow: "A recent case",
    caseTitle: "Scaling, then a gentle whiten",
    caseBody: "Tea and coffee stains on healthy enamel. We scaled first, then whitened in the clinic. No drilling, and no veneers.",
    rows: [
      { label: "Concern", value: "Surface stains, dull enamel" },
      { label: "Treatment", value: "Scaling and in-office whitening" },
      { label: "Time", value: "Two visits, two weeks apart" },
      { label: "Result", value: "Cleaner colour, natural shine" },
    ],
    discuss: "Talk about your own case",
  },
  booking: {
    eyebrow: "Appointments",
    title: [{ text: "Request a time " }, { text: "that suits you", accent: true }] as TextPart[],
    lead: "Leave your name, number and the treatment you have in mind. The clinic coordinator calls within one working hour to confirm the exact time.",
    roomAlt: "A treatment room at Clinic Farda",
    calm: "A quiet room, and a clear price.",
    calmBody: "We tell you the cost before treatment starts. If something does not need treating, we say that too.",
    chips: ["Appointments this week", "Parking in the building", "Cost explained first"],
    thanks: (first: string) => (first ? `Thank you, ${first}.` : "Thank you."),
    receivedBefore: "Your request for ",
    receivedAfter: " is with the clinic. We will call to confirm the exact time.",
    another: "Send another request",
    formTitle: "Request an appointment",
    requiredNote: "Fields marked * are required.",
    name: "Full name *",
    namePh: "Zahra Nouri",
    phone: "Mobile *",
    phonePh: "0912 123 4567",
    treatment: "Treatment",
    treatments: [
      "Examination",
      "Scaling and polish",
      "Root canal",
      "Implant",
      "Orthodontics",
      "Laminate or composite",
      "Whitening",
      "Wisdom tooth",
      "Crown, bridge or denture",
    ],
    date: "Preferred date *",
    time: "Preferred time",
    privacy: "We use this only to confirm your visit.",
  },
  about: {
    eyebrow: "The clinic",
    title: [{ text: "A practice you can " }, { text: "come back to", accent: true }] as TextPart[],
    lead: "Dr. Leila Farda opened Clinic Farda in Saadat Abad so dentistry would feel calm and specific. For twelve years the same team has followed the examination, the explanation and the treatment — not a chain of sudden referrals.",
    meet: "The people you will see",
    clinicAlt: "Reception at Clinic Farda in Saadat Abad",
    studio: "Clinic Farda, Saadat Abad",
    consultAlt: "Dr. Farda reviewing an X-ray with a patient",
    planning: "Looking at the X-ray together",
    promiseEyebrow: "How we work",
    promise: "You will know what we recommend, and why.",
    promiseBody: "A clear explanation, an honest fee, and time to decide. That is the whole method.",
    founder: "Dr. Leila Farda",
    founderRole: "Founder and dentist",
    values: [
      { title: "Twelve years of clinical work", text: "The clinic opened in 1393. Check-ups, root canals, implants and veneers are everyday work here, not a side list." },
      { title: "Pictures before decisions", text: "X-rays, photos and scans are how we explain a tooth. Treatment follows what you have actually seen." },
      { title: "One record, one team", text: "The dentist, the assistant and the coordinator share the same notes, from the first phone call to the review visit." },
      { title: "Only the treatment you need", text: "We do not fill a plan with extras. If a stain will polish off, we polish it. If a tooth can be kept, we try to keep it." },
    ],
  },
  contact: {
    eyebrow: "Visit",
    title: [{ text: "Saadat Abad, " }, { text: "Kaj Square", accent: true }] as TextPart[],
    lead: "Sarv medical building, third floor. Patients can use the building parking. Chamran and Yadegar-e Emam are the simplest ways in.",
    rows: [
      { k: "Address", v: "No. 42, Sarv-e Gharbi, Kaj Square", s: "Saadat Abad, Tehran · third floor" },
      { k: "Phone", v: "021-2239 4040", s: "Same-day calls: 0912-440 4040" },
      { k: "Email", v: "info@clinicfarda.ir", s: "We usually reply the same working day" },
      { k: "Hours", v: "Sat – Wed, 8:30 – 20:00", s: "Thursday 8:30 – 15:00 · Friday closed" },
    ],
    mapTitle: "Clinic Farda",
    mapSub: "Kaj Square, Sarv-e Gharbi · open today until 20:00",
    directions: "Directions",
    directionsHref: "https://www.google.com/maps/search/?api=1&query=Kaj+Square+Sarv+Street+Saadat+Abad+Tehran",
  },
  footer: {
    blurb: "Clinic Farda is a dental practice in Saadat Abad, Tehran. Examinations, root canals, implants, veneers and braces — explained before they begin.",
    instagram: "Instagram",
    facebook: "Facebook",
    linkedin: "LinkedIn",
    navigation: "Navigation",
    contact: "Contact",
    rights: (year: number) => `© ${year} Clinic Farda. All rights reserved.`,
    privacy: "Privacy",
    terms: "Terms",
    accessibility: "Accessibility",
    toTop: "Back to top",
    address: "No. 42, Sarv-e Gharbi, Kaj Square, Tehran",
    hours: "Sat – Wed, 8:30 – 20:00",
    phone: "021-2239 4040",
    phoneHref: "tel:+982122394040",
    email: "info@clinicfarda.ir",
    emailHref: "mailto:info@clinicfarda.ir",
  },
  theme: {
    mode: "Colour mode",
    toLight: "Switch to light",
    toDark: "Switch to dark",
    colors: "Theme colours",
    primary: "Primary",
    secondary: "Secondary",
    preset: "Palettes",
    light: "Light",
    dark: "Dark",
  },
};

const fa: typeof en = {
  meta: { title: "کلینیک فردا — دندان‌پزشکی آرام و دقیق در سعادت‌آباد" },
  langLabel: "زبان",
  brand: "کلینیک فردا",
  brandHome: "کلینیک فردا — صفحهٔ اصلی",
  nav: [
    { label: "خانه", href: "#top" },
    { label: "خدمات", href: "#services" },
    { label: "درباره", href: "#about" },
    { label: "نظرات", href: "#reviews" },
    { label: "تماس", href: "#contact" },
  ],
  book: "رزرو نوبت",
  openMenu: "باز کردن منو",
  closeMenu: "بستن منو",
  navPrimary: "اصلی",
  navMobile: "موبایل",
  headerHours: "شنبه تا چهارشنبه · ۸:۳۰ تا ۲۰ · ۰۲۱-۲۲۳۹۴۰۴۰",
  stars: (n: number) => `${n} از ۵ ستاره`,
  hero: {
    messages: ["معاینه و جرم‌گیری", "ایمپلنت و روکش", "کامپوزیت و لمینت", "ارتودنسی", "طراحی لبخند"],
    lines: [
      [{ text: "مراقبت" }, { text: "دندان،" }],
      [{ text: "آرام" }, { text: "و" }, { text: "با حوصله،" }],
      [{ text: "برای" }, { text: "لبخندی", highlight: true }, { text: "که بماند", highlight: true }],
    ],
    desc: "کلینیک فردا در سعادت‌آباد است. معاینه را با حوصله شروع می‌کنیم، آنچه می‌بینیم را نشان می‌دهیم، و بعد درمان را پیشنهاد می‌کنیم؛ از جرم‌گیری و عصب‌کشی تا ایمپلنت، لمینت و ارتودنسی.",
    explore: "آشنایی با کلینیک",
    trust: "اعتماد",
    patients: "مراجع",
    trustCount: "۸٬۰۰۰+",
    portraitAlt: "دکتر لیلا فردا، دندان‌پزشک و بنیان‌گذار کلینیک فردا",
    painless: "درمان با عجله شروع نمی‌شود",
    painlessSub: "طرح درمان را پیش از شروع می‌بینید",
    doctor: "دکتر لیلا فردا",
    doctorSub: "دندان‌پزشک · ۱۲ سال کار بالینی",
    scroll: "ادامه",
  },
  anatomy: {
    eyebrow: "آناتومی دندان",
    title: [{ text: "لبخند را " }, { text: "از نزدیک ببینید", accent: true }],
    lead: "مدلی از قوس دندان، لثه و خود دندان. هر بخش را انتخاب کنید تا بگوییم در درمان چه نقشی دارد؛ از مینا تا عصب.",
    live: "مدل زنده",
    hint: "بکشید تا بچرخد · روی نقطه بزنید",
    idleTitle: "یکی از بخش‌ها را انتخاب کنید",
    idleBody: "توضیح کنار مدل می‌ماند. بین مینا، عاج، پالپ، لثه، ریشه و عصب جابه‌جا شوید، بدون اینکه لازم باشد صفحه را بالا و پایین کنید.",
    cross: "یک برش ساده. هایلایت با همان بخشی که انتخاب کرده‌اید عوض می‌شود.",
    items: {
      enamel: {
        label: "مینا",
        short: "پوستهٔ بیرونی دندان",
        description: "مینا پوشش سخت و نیمه‌شفاف تاج است و دوباره ساخته نمی‌شود. برای همین در جرم‌گیری، بلیچینگ و هر کاری که به سطح دندان می‌رسد محتاطیم.",
      },
      dentin: {
        label: "عاج",
        short: "لایهٔ زیر مینا",
        description: "عاج کمی زرد است و لوله‌های ریز دارد. وقتی مینا نازک شود، سرما، شیرینی و حساسیت را همین لایه حس می‌کنید.",
      },
      pulp: {
        label: "پالپ",
        short: "بخش زندهٔ دندان",
        description: "خون‌رسانی و عصب دندان اینجاست. اگر پوسیدگی یا ترک به پالپ برسد، معمولاً برای نگه داشتن دندان باید عصب‌کشی شود.",
      },
      gum: {
        label: "لثه",
        short: "بافت دور طوق دندان",
        description: "لثهٔ سالم دور گردن دندان می‌نشیند و از استخوان محافظت می‌کند. خون‌ریزی موقع مسواک، اغلب اولین چیزی است که در معاینه به آن توجه می‌کنیم.",
      },
      root: {
        label: "ریشه",
        short: "بخشی که در فک نشسته",
        description: "بیشتر دندان زیر لثه است و با رباط نگه داشته می‌شود. ایمپلنت وقتی جای این ریشه را می‌گیرد که خود ریشه دیگر قابل نگهداری نباشد.",
      },
      nerve: {
        label: "عصب",
        short: "حس داخل کانال",
        description: "عصب از نوک ریشه وارد می‌شود. در عصب‌کشی این کانال تمیز و پر می‌شود تا دندان سر جایش بماند و درد تمام شود.",
      },
    },
  },
  services: {
    eyebrow: "خدمات کلینیک",
    title: [{ text: "درمان‌هایی که " }, { text: "واقعاً وقت می‌گیرند", accent: true }] as TextPart[],
    lead: "این‌ها کارهایی است که مراجعان کلینیک فردا بیشتر برایشان نوبت می‌گیرند. اگر نمی‌دانید کدام به شما مربوط است، جلسهٔ اول فقط معاینه است.",
    plan: "وقت معاینه بگیرید",
    more: "دربارهٔ این درمان بپرسید",
    items: [
      {
        title: "معاینه و جرم‌گیری",
        text: "معاینهٔ کامل، عکس فقط وقتی لازم باشد، و جرم‌گیری‌ای که لثه را زخم نکند. اگر پوسیدگی یا التهاب لثه باشد، همان جلسه مسیر بعدی را مشخص می‌کنیم.",
      },
      {
        title: "عصب‌کشی",
        text: "وقتی درد یا عفونت به عصب رسیده، دندان را با درمان ریشه نگه می‌داریم. کار با بی‌حسی مناسب و معمولاً در یک یا دو جلسه انجام می‌شود. روکش را جداگانه و از قبل هماهنگ می‌کنیم، نه سرِ یونیت.",
      },
      {
        title: "ایمپلنت",
        text: "پایهٔ تیتانیوم به‌جای ریشه، و روکش سرامیکی به‌جای تاج. پیش از جراحی استخوان و لثه را می‌بینیم و صادقانه می‌گوییم جوش خوردن چقدر طول می‌کشد.",
      },
      {
        title: "ارتودنسی",
        text: "نامرتبی دندان و مشکل بایت، با براکت فلزی یا سرامیکی، و الاینر شفاف فقط وقتی واقعاً انتخاب درستی باشد. مدت درمان و مراقبت روزانه را قبل از شروع روی طرح نشان می‌دهیم.",
      },
      {
        title: "لمینت و کامپوزیت",
        text: "برای رنگ، شکل، یا فاصله‌های کوچک. کامپوزیت معمولاً سریع‌تر است و لمینت سرامیکی ماندگارتر. هر دو را با رنگ دندان‌های کناری تنظیم می‌کنیم تا لبخند مصنوعی نشود.",
      },
      {
        title: "بلیچینگ",
        text: "سفید کردن در مطب برای لکهٔ چای، قهوه و دخانیات، روی مینای سالم. اگر دندان حساس باشد روش را ملایم‌تر می‌کنیم. قول سفیدِ غیرطبیعی نمی‌دهیم.",
      },
      {
        title: "دندان عقل",
        text: "اگر دندان عقل نهفته است، به دندان کناری فشار می‌آورد، یا لثه را مرتب ملتهب می‌کند، کشیدن را با عکس برنامه‌ریزی می‌کنیم و دربارهٔ تورم، بخیه و روزهای بعد حرف می‌زنیم.",
      },
      {
        title: "روکش، بریج و پروتز",
        text: "روکش، دندان عصب‌کشی‌شده یا شکسته را حفظ می‌کند. اگر چند دندان از دست رفته باشد، بریج یا پروتز را متناسب با لثه و عادت جویدن شما می‌سازیم، نه از روی یک قالب آماده.",
      },
    ],
    footerTitle: "خدمات",
  },
  reviews: {
    eyebrow: "از زبان مراجعان",
    title: [{ text: "حرفی که " }, { text: "بعد از درمان می‌شنویم", accent: true }],
    photoAlt: "لبخند یک مراجع بعد از درمان در کلینیک فردا",
    real: "مراجعان کلینیک",
    consent: "با اجازه منتشر شده",
    pill: "۴٫۹ ★ · بیش از ۱٬۲۰۰ نظر",
    tabs: "نظرات",
    tab: (n: number) => `نظر ${n}`,
    prev: "نظر قبلی",
    next: "نظر بعدی",
    items: [
      {
        quote: "سال‌ها عصب‌کشی را عقب انداخته بودم. دکتر فردا اول عکس را نشانم داد و گفت جلسه دقیقاً چه حسی دارد. همان روز تمام شد و شب راحت خوابیدم.",
        name: "زهرا نوری",
        treatment: "عصب‌کشی و روکش",
      },
      {
        quote: "برای کامپوزیت آمده بودم و می‌ترسیدم دندان‌هایم زیادی سفید شود. رنگ را با دندان‌های کناری تنظیم کردند. همسرم کار را نفهمید؛ فقط گفت بیشتر لبخند می‌زنی.",
        name: "سارا محمدی",
        treatment: "کامپوزیت ونیر",
      },
      {
        quote: "ایمپلنت فک پایین را بعد از بررسی استخوان شروع کردیم. زمان جوش خوردن را از روز اول گفتند و برای روکش عجله نکردند. موقع غذا فرق خاصی با دندان خودم حس نمی‌کنم.",
        name: "رضا کریمی",
        treatment: "ایمپلنت",
      },
      {
        quote: "ارتودنسی را بعد از سی‌سالگی شروع کردم. براکت سرامیکی انتخاب کردیم و هر بار پیشرفت را روی عکس نشانم می‌دادند. خود کلینیک هم شلوغ و پرسرصدا نیست.",
        name: "مریم حسینی",
        treatment: "ارتودنسی",
      },
    ],
  },
  stats: {
    eyebrow: "چرا کلینیک فردا",
    title: [{ text: "جایی که " }, { text: "دوباره برمی‌گردید", accent: true }],
    items: [{ label: "سال فعالیت" }, { label: "مراجع" }, { label: "بازگشت دوباره" }, { label: "میانگین امتیاز" }],
  },
  results: {
    eyebrow: "قبل و بعد",
    title: [{ text: "همان لبخند، " }, { text: "بعد از درمان", accent: true }],
    lead: "خط را بکشید. سمت چپ دندان‌ها پیش از جرم‌گیری و بلیچینگ است و سمت راست همان عکس، بعد از درمان. لب و پوست دست نخورده‌اند.",
    slider: "مقایسهٔ قبل و بعد",
    beforeAlt: "لبخند پیش از جرم‌گیری و بلیچینگ، با دندان‌های لکه‌دار",
    afterAlt: "همان لبخند بعد از درمان، کمی روشن‌تر و تمیزتر",
    before: "قبل",
    after: "بعد",
    caseEyebrow: "یک پروندهٔ اخیر",
    caseTitle: "جرم‌گیری، بعد بلیچینگ ملایم",
    caseBody: "لکهٔ چای و قهوه روی مینای سالم. اول جرم‌گیری، بعد سفید کردن در مطب. بدون تراش و بدون لمینت.",
    rows: [
      { label: "موضوع", value: "لکهٔ سطحی و مینای کدر" },
      { label: "درمان", value: "جرم‌گیری و بلیچینگ مطب" },
      { label: "زمان", value: "دو جلسه، به فاصلهٔ دو هفته" },
      { label: "نتیجه", value: "رنگ تمیزتر، درخشش طبیعی" },
    ],
    discuss: "دربارهٔ دندان خودتان حرف بزنیم",
  },
  booking: {
    eyebrow: "نوبت",
    title: [{ text: "ساعتی را " }, { text: "که برایتان مناسب است", accent: true }, { text: " بگویید" }],
    lead: "نام، شماره و درمانی که در ذهن دارید را بنویسید. هماهنگ‌کنندهٔ کلینیک تا یک ساعت کاری برای قطعی کردن وقت تماس می‌گیرد.",
    roomAlt: "اتاق درمان کلینیک فردا",
    calm: "اتاق خلوت، و هزینهٔ روشن.",
    calmBody: "هزینه را پیش از شروع درمان می‌گوییم. اگر کاری لازم نباشد، همان را هم رک می‌گوییم.",
    chips: ["نوبت در همین هفته", "پارکینگ ساختمان", "هزینه، قبل از شروع"],
    thanks: (first: string) => (first ? `${first} عزیز، درخواست‌تان رسید.` : "درخواست‌تان رسید."),
    receivedBefore: "درخواست شما برای ساعت ",
    receivedAfter: " ثبت شد. برای قطعی کردن وقت تماس می‌گیریم.",
    another: "درخواست دیگری بفرستید",
    formTitle: "درخواست نوبت",
    requiredNote: "موارد ستاره‌دار لازم است.",
    name: "نام و نام خانوادگی *",
    namePh: "زهرا نوری",
    phone: "موبایل *",
    phonePh: "۰۹۱۲۱۲۳۴۵۶۷",
    treatment: "درمان",
    treatments: ["معاینه", "جرم‌گیری", "عصب‌کشی", "ایمپلنت", "ارتودنسی", "لمینت یا کامپوزیت", "بلیچینگ", "دندان عقل", "روکش، بریج یا پروتز"],
    date: "تاریخ مورد نظر *",
    time: "ساعت مورد نظر",
    privacy: "این اطلاعات فقط برای هماهنگی نوبت استفاده می‌شود.",
  },
  about: {
    eyebrow: "کلینیک",
    title: [{ text: "مطبّی که " }, { text: "دوباره به آن سر می‌زنید", accent: true }],
    lead: "دکتر لیلا فردا کلینیک را در سعادت‌آباد راه انداخت تا دندان‌پزشکی شلوغ و مبهم نباشد. دوازده سال است معاینه، توضیح و درمان را همین تیم دنبال می‌کند؛ نه یک زنجیره از ارجاع‌های ناگهانی.",
    meet: "کسانی که می‌بینید",
    clinicAlt: "پذیرش کلینیک فردا در سعادت‌آباد",
    studio: "کلینیک فردا، سعادت‌آباد",
    consultAlt: "دکتر فردا در حال دیدن عکس دندان با مراجع",
    planning: "دیدن عکس، با هم",
    promiseEyebrow: "روش کار",
    promise: "می‌دانید چه پیشنهادی می‌دهیم، و چرا.",
    promiseBody: "توضیح روشن، هزینهٔ صادقانه، و وقت برای تصمیم. روش کار همین است.",
    founder: "دکتر لیلا فردا",
    founderRole: "بنیان‌گذار و دندان‌پزشک",
    values: [
      { title: "دوازده سال کار بالینی", text: "کلینیک از سال ۱۳۹۳ باز است. معاینه، عصب‌کشی، ایمپلنت و لمینت کار هرروز اینجاست، نه یک فهرست تزئینی." },
      { title: "اول عکس، بعد تصمیم", text: "رادیوگرافی، عکس و اسکن راه توضیح دادن دندان است. درمان بعد از چیزی می‌آید که خودتان دیده‌اید." },
      { title: "یک پرونده، یک تیم", text: "دندان‌پزشک، دستیار و هماهنگ‌کننده از اولین تماس تا جلسهٔ کنترل همان یادداشت‌ها را دارند." },
      { title: "فقط درمانی که لازم است", text: "طرح را با کار اضافه پر نمی‌کنیم. اگر لکه با جرم‌گیری برود، جرم‌گیری می‌کنیم. اگر دندان قابل نگهداری باشد، نگه‌اش می‌داریم." },
    ],
  },
  contact: {
    eyebrow: "مراجعه",
    title: [{ text: "سعادت‌آباد، " }, { text: "میدان کاج", accent: true }],
    lead: "ساختمان پزشکان سرو، طبقهٔ سوم. پارکینگ ساختمان برای مراجعان باز است. رسیدن از چمران و یادگار امام ساده‌تر است.",
    rows: [
      { k: "نشانی", v: "سرو غربی، میدان کاج، پلاک ۴۲", s: "سعادت‌آباد، تهران · طبقهٔ سوم" },
      { k: "تلفن", v: "۰۲۱-۲۲۳۹۴۰۴۰", s: "هماهنگی همان‌روز: ۰۹۱۲-۴۴۰۴۰۴۰" },
      { k: "ایمیل", v: "info@clinicfarda.ir", s: "معمولاً همان روز کاری جواب می‌دهیم" },
      { k: "ساعت کاری", v: "شنبه تا چهارشنبه، ۸:۳۰ تا ۲۰", s: "پنجشنبه ۸:۳۰ تا ۱۵ · جمعه تعطیل" },
    ],
    mapTitle: "کلینیک فردا",
    mapSub: "میدان کاج، سرو غربی · امروز تا ۲۰ باز است",
    directions: "مسیر",
    directionsHref: "https://www.google.com/maps/search/?api=1&query=Kaj+Square+Sarv+Street+Saadat+Abad+Tehran",
  },
  footer: {
    blurb: "کلینیک فردا مطب دندان‌پزشکی در سعادت‌آباد تهران است. معاینه، عصب‌کشی، ایمپلنت، لمینت و ارتودنسی؛ با توضیح، قبل از شروع.",
    instagram: "اینستاگرام",
    facebook: "فیسبوک",
    linkedin: "لینکدین",
    navigation: "دسترسی",
    contact: "تماس",
    rights: (year: number) => `© ${year} کلینیک فردا. همهٔ حقوق محفوظ است.`,
    privacy: "حریم خصوصی",
    terms: "شرایط",
    accessibility: "دسترسی",
    toTop: "بالای صفحه",
    address: "سرو غربی، میدان کاج، پلاک ۴۲، تهران",
    hours: "شنبه تا چهارشنبه، ۸:۳۰ تا ۲۰",
    phone: "۰۲۱-۲۲۳۹۴۰۴۰",
    phoneHref: "tel:+982122394040",
    email: "info@clinicfarda.ir",
    emailHref: "mailto:info@clinicfarda.ir",
  },
  theme: {
    mode: "حالت رنگ",
    toLight: "حالت روشن",
    toDark: "حالت تیره",
    colors: "ترکیب رنگ",
    primary: "رنگ اصلی",
    secondary: "رنگ دوم",
    preset: "پالت‌ها",
    light: "روشن",
    dark: "تیره",
  },
};

export const COPY: Record<Lang, typeof en> = { en, fa };
export type Copy = typeof en;
